spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
